language: node_js
node_js:
- '13'
script:
- cd tests
- npm install
- npm run test
notifications:
  slack:
    rooms:
      secure: Xt1n8HOjEf7laksSneKjjbfkUJMDInEBqyl3Ct9UOgtQ4Vd7PdztXEu/jP93OBa8I977dkdmLFUgBpBLMpAcvdMM2XVWX1g6NKIucs62HlnUf9c0rqiA0kOtpQrkNIksNeyBh3GlQfuQBZ7/z14CWunt/V/pj9dJowNT7KuPqz6DWfwuwuK7SWxUV/tcIXz3x79+EzDm1TSLNqUfumdavhad3j4f+KCX8tt8NKhZdCS+u0/2bcD4Yk0ZeUESZxUoBmxxN184QieBp1mwD09+nK+ACNhRbNAu2/Oxtk029+0YnTlg6Uj9vgJcfKP8+uXRE3Pk1b83whDObXKwsMUgMLR8B0Mmv14wlPemI5QCBowSlw0UCfNauy7iBFbH0UWZgTcAan1FuH2DcgGkSF5Ic1uIx0aBPcvSJj8S3BYvZPs5Cbx03goAZllur0pltXpqbfmJIceVAoYJsGgVvqyJgKIMyWHTS/Q8/Y5FMkuIl5ZY+Ocie3mNvBLb2VLbUi9N18R1CKYjj1vrYfh2pBTntLmlBe1dsPZTLZLYxQdtdxyhnepaqRqKRyBI4C4GpmYU54FvbwpNcXgQHPIAhTLn46KqL91tjqUWI9jgw8GGnunnI1yUArCbqkt0Prcsh74oj7+Nq8mdIIjE0aEjxmKdgD2Zt8P+l4sKzipJsjdgu/E=
