language: node_js
node_js:
- '13'
script:
- cd tests
- npm install
- npm run test
notifications:
  slack:
    rooms:
      secure: jzDs8UKTEjNZtS618kOctrjUXeItah/gXjON18mAGKYKTAp8zquhNx/Cyu8qyxvvEcMtQkjno7qNSfD6ruPqrRPSUCby6sYkvT43gS6QB2HHPf2LVqT6icqK9WtYq6hIaxpXi8XmZiYyGGoPLK0ypb/jveMyF8w80y8knkFlM/hcxwAILY/XSrH0JfyqwbgTZ5QW3syrops8j22cvtEyy4L/u4du7gNoXKLTlaOz3Z854FGgBQROZqPYgrO2Oy4Mj5weL70dfEz6HBLm6GBDcgYC3gT21WYjo8NSHkzIcEYeZJm/WRfrvpe8nlOmBC9Z/Up5Utbognz+OaM6JrfQs806U591SF6VBMB8/tA0R4YTzYUP5BmbXOh2blfoX13FMCpAGiozUBVYWUGswShWiojxtcsKqgmXITG/AICIEM+MRWMO4/sjKImU7wy3IUDjUH+FbzHJEfYw2LKYOHkVcyzsNKdUxSdONLR7kww7uxnSJ5pN7D6XKh5myhfShdnBzQv1VU4y16yxzSO4i7iRdA/upwvT5LR4GXtbNN6JchATxNMS58dqG3rpkhTtPi25jKINPM637Woc9oJ6KB+kXLCr2k/Tj7M4Cx5eS1Uuwb8Ch0OTb11RMt/cVGSUiA2ygz8VKngTi1g4Fw5a0W3dRKnPk7sHdMKjvnFR62u3UBE=
