language: node_js
node_js:
- '13'
script:
- cd tests
- npm install
- npm run test
notifications:
  slack:
    rooms:
      secure: M3CYvHeMVCz+TtW34zM5r1pXM4U5Nkbk1QXx0QYfWp25K9R48h1er+VfXBChzHicgaAiHNDewzzBIb+c2dO1S/MpL1joYGkeG54in1B7SWFHy+m83cygJRQVetcYccGTRGnsDdg/SjJCC9yna0RXvQxrslQhFSFK1u0DMFMXvkVaieIhVkOQMz8rAFhTfQOaYg2aUcNVLah6/DMrYb/HwqR0e5FhapTIJpT2N3fZXxvO4QZiWbGi22sSP+JFq4tz9oRvykBPsxAWq9pq8mpkNKjhHleZ5bdEfP1oRzOQK2LHie76aoI0OLGTSjGvv4ZuDBj3ho6AluRjNKqsapYiM8A9y+nXdHuJsKF+tt+SwtG3OcAttB2bfhn8CxCS6rA3psBp9BxTFLGHFDVa2oUvbaZO7CuDWrQILRm533eCX/yu3l2jZx9wgO706wcPXstx3rLaC/fWMvwKJ16wbL1YJ44L/Cos5AjABQ2gEyExRehJNT/xeiiXnl1qL1DYOxVVwu5zMCeeIu3/QI+gOmBsFIH3j/IBzsHUUCicsZXM3RnexN7vJJYA3KcHrvqcqOYHLmWs2HvMFLBmbVmIw39xo5w5JSuJKb4Tfd1Ef9SXsEdk1vXOesSihJU5TXjRbxkdZ7T4HmKi/HSRiaQp2Yi8JoCUZPmkwUGMJzvSwC3UsUY=
