language: node_js
node_js:
- '13'
script:
- cd tests
- npm install
- npm run test
notifications:
  slack:
    rooms:
      secure: WIY+cwd3NliceTOpgNG4AjBrGffuhzsDG0e4SFwwiD01CeZ5SHQicLlQxd7AWDGVKj0DJb1TqfbH3KzLgxzuf6AZrIBeUil03qdSxcgiqUdB6wF+LibkTW5JMBdtyzQrk/XtXsKNwuZjuGXz+Yocxanog+CRDRaxG8pJ65t3KuKygNDgZrywzwJHr6vi43kT3DiilHUSs9scE3+R+PxIGO2CUIRdFvyc6xRN+qAFmjvZf9lmrQhGtkWSoOihcUIxjHaQtbkGW78bQYKxHCqOqJL7RQ950orGEBe/NjzsIcd94/2gTkK++zCBBV4J4YsXn5KAtziSw790HaolNaQrsoVXL7rEnLtZJgOB08UsHTAPjudCWUMXxFpswUOqBgaEb6Pn7Q+3aTD1BYoc6pvwgQ+p+9jlFZDpdR+U+9PgB73dFf0scbGee+k+OMeX2M4gaD+HqDOAIoOpbP2l8Ixr8SjFL88qJOurynplsA7TKGiY+GGXWTDieG6xDOt8C/dRbflpEGxm9sH0oXrbNJPA7tJsLZt76sc5tueoOpro9S0rBGqtsXmR2tdH4CahVa9v0xH8PYl/itnRg1v94cmNkNL22rjcvUeZAJpUbOev3DpvLG9RnhUK+Qevoc/jZdoDzBlHnLkRTzQPJmrso8CI8GwW16asf81D5oZtiV2MriQ=
